<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produit;

class ProduitSeeder extends Seeder
{
    public function run()
    {
        $produits = [
            [
                'nom' => 'Valise noire renforcée',
                'description' => 'Valise rigide avec roulettes, parfaite pour les longs voyages.',
                'prix' => 349.99,
                'stock' => 20,
                'image' => 'images/produits/3valise.jpg',
            ],
            [
                'nom' => 'Caméra de poche',
                'description' => 'Caméra compacte idéale pour capturer vos souvenirs de voyage.',
                'prix' => 459.50,
                'stock' => 12,
                'image' => 'images/produits/camera.jpeg',
            ],
            [
                'nom' => 'Caméra HD portable',
                'description' => 'Petite caméra avec qualité HD pour vos aventures.',
                'prix' => 389.90,
                'stock' => 9,
                'image' => 'images/produits/camera3.jpg',
            ],
            [
                'nom' => 'Caméra moderne 4K',
                'description' => 'Caméra dernier cri avec qualité 4K pour les professionnels du voyage.',
                'prix' => 499.99,
                'stock' => 5,
                'image' => 'images/produits/cameramoderne.jpeg',
            ],
            [
                'nom' => 'Tente de camping compacte',
                'description' => 'Équipement essentiel pour les amateurs de camping.',
                'prix' => 269.99,
                'stock' => 18,
                'image' => 'images/produits/camp.jpg',
            ],
            [
                'nom' => 'Cartable pour voyage',
                'description' => 'Cartable pratique pour les courts déplacements.',
                'prix' => 189.99,
                'stock' => 15,
                'image' => 'images/produits/cartable.jpg',
            ],
            [
                'nom' => 'Ciseaux multifonctions',
                'description' => 'Accessoire indispensable pour vos kits de voyage.',
                'prix' => 129.50,
                'stock' => 25,
                'image' => 'images/produits/ciseaux.jpg',
            ],
            [
                'nom' => 'Balance de voyage',
                'description' => 'Petite balance pour peser vos bagages facilement.',
                'prix' => 149.00,
                'stock' => 30,
                'image' => 'images/produits/équilibre.jpeg',
            ],
            [
                'nom' => 'Lampe de camping LED',
                'description' => 'Lampe rechargeable pour vos soirées en plein air.',
                'prix' => 199.00,
                'stock' => 20,
                'image' => 'images/produits/lampa.jpeg',
            ],
            [
                'nom' => 'Lampe classique',
                'description' => 'Lampe compacte pour les voyages de nuit.',
                'prix' => 159.99,
                'stock' => 18,
                'image' => 'images/produits/lampaclassic.jpg',
            ],
            [
                'nom' => 'Mini lampe torche',
                'description' => 'Lampe de poche résistante à l’eau, idéale pour le camping.',
                'prix' => 139.99,
                'stock' => 17,
                'image' => 'images/produits/lampe1.jpg',
            ],
            [
                'nom' => 'Kit d’outils de voyage',
                'description' => 'Kit compact avec les outils essentiels pour vos déplacements.',
                'prix' => 219.50,
                'stock' => 10,
                'image' => 'images/produits/Outils de voyage.jpg',
            ],
            [
                'nom' => 'Porte passeport en cuir',
                'description' => 'Gardez vos documents de voyage en sécurité.',
                'prix' => 89.99,
                'stock' => 28,
                'image' => 'images/produits/passport.jpeg',
            ],
            [
                'nom' => 'Sac médical de secours',
                'description' => 'Petit sac avec kit de premiers soins pour vos sorties.',
                'prix' => 179.99,
                'stock' => 15,
                'image' => 'images/produits/sacmedical.jpg',
            ],
            [
                'nom' => 'Sac de voyage classique',
                'description' => 'Sac résistant et spacieux pour transporter vos affaires.',
                'prix' => 219.00,
                'stock' => 22,
                'image' => 'images/produits/sac.jpg',
            ],
            [
                'nom' => 'Petit sac pratique',
                'description' => 'Sac compact parfait pour les randonnées courtes.',
                'prix' => 159.00,
                'stock' => 19,
                'image' => 'images/produits/sac1.jpeg',
            ],
            [
                'nom' => 'Sac léger pour femme',
                'description' => 'Design élégant avec espace optimisé.',
                'prix' => 189.00,
                'stock' => 14,
                'image' => 'images/produits/sac3.jpeg',
            ],
            [
                'nom' => 'Sac de voyage robuste',
                'description' => 'Conçu pour les longs trajets avec grande capacité.',
                'prix' => 239.00,
                'stock' => 11,
                'image' => 'images/produits/sac4.jpeg',
            ],
            [
                'nom' => 'Sac de sport compact',
                'description' => 'Idéal pour les courts séjours et les salles de sport.',
                'prix' => 149.50,
                'stock' => 16,
                'image' => 'images/produits/sac5.jpg',
            ],
            [
                'nom' => 'Sac en toile imperméable',
                'description' => 'Parfait pour toutes conditions météorologiques.',
                'prix' => 179.99,
                'stock' => 13,
                'image' => 'images/produits/sac6.jpg',
            ],
            [
                'nom' => 'Sac avec produits essentiels',
                'description' => 'Contient les essentiels pour un voyage rapide.',
                'prix' => 199.99,
                'stock' => 8,
                'image' => 'images/produits/sacproduits.jpg',
            ],
            [
                'nom' => 'Tasse isotherme de voyage',
                'description' => 'Gardez vos boissons chaudes pendant vos trajets.',
                'prix' => 99.99,
                'stock' => 24,
                'image' => 'images/produits/tasse.jpg',
            ],
            [
                'nom' => 'Valise élégante',
                'description' => 'Valise rigide avec poignées confortables.',
                'prix' => 329.99,
                'stock' => 10,
                'image' => 'images/produits/valise.jpg',
            ],
            [
                'nom' => 'Valise souple',
                'description' => 'Facile à transporter avec plusieurs compartiments.',
                'prix' => 279.99,
                'stock' => 14,
                'image' => 'images/produits/valise2.jpg',
            ], 
            [
                'nom' => 'Caméra sportive 7',
                'description' => 'Caméra adaptée aux conditions extrêmes, parfaite pour les activités outdoor.',
                'prix' => 429.99,
                'stock' => 10,
                'image' => 'images/produits/camera7.jpeg',
            ],
            [
                'nom' => 'Caméra résistante 8',
                'description' => 'Caméra compacte avec résistance à l’eau et au choc.',
                'prix' => 459.99,
                'stock' => 9,
                'image' => 'images/produits/camera8.jpeg',
            ],
            [
                'nom' => 'Caméra voyage 9',
                'description' => 'Design ergonomique et idéale pour capturer vos souvenirs.',
                'prix' => 379.99,
                'stock' => 7,
                'image' => 'images/produits/camera9.jpeg',
            ],
            [
                'nom' => 'Caméra numérique 10',
                'description' => 'Idéale pour les voyages et les photos de paysages.',
                'prix' => 399.00,
                'stock' => 11,
                'image' => 'images/produits/camera10.jpeg',
            ],
            [
                'nom' => 'Caméra HD 11',
                'description' => 'Qualité d’image excellente avec une autonomie longue durée.',
                'prix' => 415.00,
                'stock' => 6,
                'image' => 'images/produits/camera11.jpeg',
            ],
            [
                'nom' => 'Caméra compact 12',
                'description' => 'Compacte, légère et facile à transporter en voyage.',
                'prix' => 385.00,
                'stock' => 10,
                'image' => 'images/produits/camera12.jpeg',
            ],
            [
                'nom' => 'Lampe de camping ultra-lumineuse',
                'description' => 'Lampe LED avec grande autonomie et intensité réglable.',
                'prix' => 169.99,
                'stock' => 14,
                'image' => 'images/produits/lampe3.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 7',
                'description' => 'Conçue pour 3 personnes, avec moustiquaire intégrée.',
                'prix' => 349.99,
                'stock' => 8,
                'image' => 'images/produits/Tente de camping7.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 8',
                'description' => 'Tente spacieuse avec double-toit pour éviter l’humidité.',
                'prix' => 379.99,
                'stock' => 9,
                'image' => 'images/produits/Tente de camping8.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 9',
                'description' => 'Structure solide et montage facile en moins de 10 minutes.',
                'prix' => 399.00,
                'stock' => 10,
                'image' => 'images/produits/Tente de camping9.jpeg',
            ],
            [
                'nom' => 'valise ',
                'description' => 'Structure solide et montage facile en moins de 10 minutes.',
                'prix' => 399.00,
                'stock' => 10,
                'image' => 'images/produits/valise0.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 10',
                'description' => 'Idéale pour les familles avec grande capacité intérieure.',
                'prix' => 429.99,
                'stock' => 6,
                'image' => 'images/produits/Tente de camping10.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 11',
                'description' => 'Isolation thermique et résistance au vent.',
                'prix' => 459.00,
                'stock' => 7,
                'image' => 'images/produits/Tente de camping11.jpeg',
            ],
            [
                'nom' => 'Tente de camping modèle 12',
                'description' => 'Tente légère pour les randonnées avec montage rapide.',
                'prix' => 319.99,
                'stock' => 12,
                'image' => 'images/produits/Tente de camping13.jpeg',
            ],
            [
                'nom' => 'Tente classique de randonnée',
                'description' => 'Tente imperméable parfaite pour les bivouacs en montagne.',
                'prix' => 299.00,
                'stock' => 13,
                'image' => 'images/produits/tente.jpeg',
            ],
            [
                'nom' => 'Tente compacte 7',
                'description' => 'Convient pour 1 à 2 personnes, avec ventilation efficace.',
                'prix' => 289.50,
                'stock' => 10,
                'image' => 'images/produits/tente7.jpeg',
            ],
            [
                'nom' => 'Valise de voyage 7',
                'description' => 'Grande valise avec système de sécurité intégré.',
                'prix' => 369.99,
                'stock' => 8,
                'image' => 'images/produits/valise7.jpeg',
            ],
            [
                'nom' => 'Valise compacte 9',
                'description' => 'Valise rigide pour les courts séjours.',
                'prix' => 309.99,
                'stock' => 9,
                'image' => 'images/produits/valise9.jpeg',
            ],
            [
                'nom' => 'Cartable voyage en cuir',
                'description' => 'Cartable élégant en cuir parfait pour les déplacements professionnels.',
                'prix' => 249.99,
                'stock' => 12,
                'image' => 'images/produits/cartable3.jpeg',
            ],
            [
                'nom' => 'Cartable vintage',
                'description' => 'Cartable au style rétro avec compartiments spacieux.',
                'prix' => 199.99,
                'stock' => 10,
                'image' => 'images/produits/cartable4.jpeg',
            ],
            [
                'nom' => 'Cartable résistant',
                'description' => 'Idéal pour les étudiants voyageurs, très robuste.',
                'prix' => 179.99,
                'stock' => 18,
                'image' => 'images/produits/cartable5.jpeg',
            ],
            [
                'nom' => 'Cartable léger pour voyage',
                'description' => 'Parfait pour transporter vos essentiels de manière compacte.',
                'prix' => 159.99,
                'stock' => 20,
                'image' => 'images/produits/cartable6.jpeg',
            ],
            [
                'nom' => 'Cartable moderne multifonction',
                'description' => 'Avec port USB intégré et design contemporain.',
                'prix' => 269.99,
                'stock' => 15,
                'image' => 'images/produits/cartable7.jpeg',
            ],
            [
                'nom' => 'Oreiller de voyage ergonomique',
                'description' => 'Oreiller mémoire de forme pour un confort optimal pendant vos trajets.',
                'prix' => 129.99,
                'stock' => 22,
                'image' => 'images/produits/oreiller.jpeg',
            ],
            
            [
                'nom' => 'Valise cabine 10',
                'description' => 'Format cabine autorisé en avion avec 4 roues silencieuses.',
                'prix' => 299.99,
                'stock' => 7,
                'image' => 'images/produits/valise10.jpeg',
            ],
            [
                'nom' => 'Valise résistante 13',
                'description' => 'Parfaite pour les longues distances et trajets fréquents.',
                'prix' => 389.99,
                'stock' => 5,
                'image' => 'images/produits/valise13.jpeg',
            ],
            [
                'nom' => 'Tente d’aventure 1',
                'description' => 'Parfaite pour les expéditions et climats extrêmes.',
                'prix' => 449.99,
                'stock' => 4,
                'image' => 'images/produits/Tente de camping1.jpeg',
            ],
            
        ];

        foreach ($produits as $produit) {
            Produit::create($produit);
        }
    }
}
